[package]
name = "converter_to_imp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calc = "0.4.0"
meval = "0.2.0"
